mod_badges = [
	"connector=!sinytra_neoforge, !library, core",
	"connectorextras=!sinytra_neoforge, !library, core",
	"fabric_api=!sinytra_neoforge, !library, core",
	"trinkets=sinytra_fabric, library",
	"accessories=library",
	"architectury=library",
	"azurelibarmor=library",
	"balm=library",
	"bookshelf=library",
	"cloth_config=library",
	"collective=library",
	"configurable=library",
	"creativecore=library",
	"curios=library",
	"fzzy_config=library",
	"gml=library",
	"konkrete=library",
	"kotlinforforge=library",
	"melody=library",
	"midnightlib=library",
	"mru=library",
	"octolib=library",
	"owo=library",
	"playeranimator=library",
	"prickle=library",
	"puzzleslib=library",
	"resourcefullib=library",
	"yet_another_config_lib_v3=library",
	"continuity=!sinytra_fabric, sinytra_neoforge",
	"accessories_compat_layer=!sinytra_neoforge, patches",
	  "bl_accessories_layer=!sinytra_neoforge, patches",
	"attributefix=!sinytra_neoforge, patches",
	  "maxhealthfix=!sinytra_neoforge, patches",
	"badhorsefix=!sinytra_neoforge, patches",
	"bettercombatextension=!sinytra_fabric, patches",
	"citresewn_neopatcher=!sinytra_neoforge, patches",
	"irisblockcompat=!sinytra_neoforge, patches",
	"modelfix=!sinytra_neoforge, patches",
	"sspb=!sinytra_neoforge, patches",
	"mr_terralith_biomesaplings=!sinytra_neoforge, patches",
	"mod_menu=!sinytra_neoforge, ports",
	"better_tooltips=!sinytra_neoforge, ports",
	"eatinganimation=!sinytra_neoforge, ports",
	"explosiveenhancement=!sinytra_neoforge, ports",
	"fallingleaves=!sinytra_neoforge, ports",
	"krypton_fnp=!sinytra_neoforge, ports",
	"mixintracereforged=!sinytra_neoforge, ports",
	"emi=!sinytra_neoforge, qol",
	  "emiffect=!sinytra_neoforge, qol",
	  "emi_enchanting=!sinytra_neoforge, qol",
	  "extra_mod_integrations=!sinytra_neoforge, qol",
	  "emi_loot=!sinytra_neoforge, qol",
	  "emi_ores=!sinytra_neoforge, qol",
	  "emixx=!sinytra_neoforge, qol",
	  "emiprofessions=!sinytra_neoforge, qol",
	  "toomanyrecipeviewers=!sinytra_neoforge, qol",
	"jade=!sinytra_neoforge, qol",
	"naturescompass=!sinytra_neoforge, qol",
	  "explorerscompass=!sinytra_neoforge, qol",
	"xaeroworldmap=!sinytra_neoforge, qol",
	  "xaerominimap=!sinytra_neoforge, qol",
	"bundleapi=!sinytra_neoforge, rpg_series, library",
	"ranged_weapon_api=!sinytra_neoforge, rpg_series, library",
	"shield_api=!sinytra_neoforge, rpg_series, library",
	"spell_engine=!sinytra_neoforge, rpg_series, library",
	  "spell_power=!sinytra_neoforge, rpg_series, library",
	"structure_pool_api=!sinytra_neoforge, rpg_series, library",
	"archers=!sinytra_neoforge, rpg_series",
	"armory_rpgs=!sinytra_neoforge, rpg_series",
	"arsenal=!sinytra_neoforge, rpg_series",
	"bettercombat=!sinytra_neoforge, rpg_series",
	"combat_roll=!sinytra_neoforge, rpg_series",
	"dungeon_difficulty=!sinytra_neoforge, rpg_series",
	"gazebo=!sinytra_neoforge, rpg_series",
	"jewelry=!sinytra_neoforge, rpg_series",
	"paladins=!sinytra_neoforge, rpg_series",
	"relics_rpgs=!sinytra_neoforge, rpg_series",
	"rogues=!sinytra_neoforge, rpg_series",
	"runes=!sinytra_neoforge, rpg_series",
	"skill_tree_rpgs=!sinytra_neoforge, rpg_series",
	"village_taverns=!sinytra_neoforge, rpg_series",
	"wizards=!sinytra_neoforge, rpg_series",
	"configureddefaults=!sinytra_neoforge, technical",
	"defaultoptions=!sinytra_neoforge, technical",
	"keybindhider=!sinytra_neoforge, technical",
	"resourcepackoverrides=!sinytra_neoforge, technical",
	"libraryferret=!sinytra_neoforge, worldgen, library",
	"lithostitched=!sinytra_neoforge, worldgen, library",
	"terrablender=!sinytra_neoforge, worldgen, library",
	"yungsapi=!sinytra_neoforge, worldgen, library",
	"amplified_nether=!sinytra_neoforge, worldgen",
	"awesomedungeon=!sinytra_neoforge, worldgen",
	"bettervillage=!sinytra_neoforge, worldgen",
	"chunky=!sinytra_neoforge, worldgen",
	  "chunkyborder=!sinytra_neoforge, worldgen",
	"improved_village_placement=!sinytra_neoforge, worldgen",
	"nullscape=!sinytra_neoforge, worldgen",
	"puffish_biome_dither=!sinytra_neoforge, worldgen",
	"terralith=!sinytra_neoforge, worldgen",
	  "mr_remove_terralithintromessage=!sinytra_neoforge, worldgen"
]

mod_parents = [
	"connector=fabric_api",
	"sodium=sodium_extra, reeses_sodium_options",
	"sounds=more_sounds",
	"accessories_compat_layer=bl_accessories_layer",
	"attributefix=maxhealthfix",
	"emi=emiffect, emi_enchanting, extra_mod_integrations, emi_loot, emi_ores, emixx, emiprofessions, toomanyrecipeviewers",
	"naturescompass=explorerscompass",
	"xaeroworldmap=xaerominimap",
	"spell_engine=spell_power",
	"chunky=chunkyborder",
	"terralith=mr_remove_terralithintromessage"
]

[main]
	compact_list = true
	mods_button_style = "REPLACE_REALMS"
	mod_count_location = "NONE"
	easter_eggs = false

[hide]
	show_libraries = true
	hide_badge = ["client"]
	hidden_mods = [
		"c2me_base",
		"c2me_client_uncapvd",
		"c2me_fixes_chunkio_threading_issues",
		"c2me_fixes_general_threading_issues",
		"c2me_fixes_worldgen_threading_issues",
		"c2me_fixes_worldgen_vanilla_bugs",
		"c2me_notickvd",
		"c2me_opts_allocs",
		"c2me_opts_chunkio",
		"c2me_opts_dfc",
		"c2me_opts_math",
		"c2me_opts_natives_math",
		"c2me_opts_scheduling",
		"c2me_opts_worldgen_general",
		"c2me_opts_worldgen_vanilla",
		"c2me_rewrites_chunk_serializer",
		"c2me_rewrites_chunk_system",
		"c2me_rewrites_chunkio",
		"c2me_server_utils",
		"c2me_threading_lighting",
		"cardinal_components",
		"cclayer",
		"citresewn_defaults",
		"commongroovylibrary",
		"conditional_mixin",
		"connectorextras_emi_bridge",
		"connectorextras_energy_bridge",
		"connectorextras_jei_bridge",
		"connectorextras_kubejs_bridge",
		"connectorextras_modmenu_bridge",
		"connectorextras_pehkui_bridge",
		"connectorextras_rei_bridge",
		"connectorextras_terrablender_bridge",
        "extra_mod_integrations_actually_additions",
        "extra_mod_integrations_chipped",
        "extra_mod_integrations_core",
        "extra_mod_integrations_farmers_delight",
        "extra_mod_integrations_irons_spellbooks",
        "extra_mod_integrations_pneumaticcraft",
        "extra_mod_integrations_rechiseled",
        "extra_mod_integrations_reliquary",
		"fabric-api",
		"forgified_fabric_api",
		"java",
        "jei",
		"kirin",
		"kuma_api",
		"lambdynlights_api",
		"lambdynlights_runtime",
		"minecraft",
		"mixinsquared",
		"modmenu",
		"neoforge",
		"placeholder_api",
		"pride",
		"spruceui",
		"tclayer",
		"tiny_config",
		"transition",
		"trender",
		"yumi_mc_core",
		"yumi_mc_libraries"
	]
	hide_mod_links = true
	hide_mod_license = true
	hide_mod_credits = true