mod_badges = [
	"bl_accessories_layer=!sinytra_neoforge, additions",
	"accessories_compat_layer=!sinytra_neoforge, additions",
	"archers_expansion=!sinytra_neoforge, additions",
	"bettercombatextension=!sinytra_fabric, additions",
	"malfu_mods=!sinytra_fabric, additions",
	"chunkyborder=!sinytra_neoforge, additions",
	"citresewn_neopatcher=!sinytra_neoforge, additions",
	"connectorextras=!sinytra_neoforge, !library, additions",
	"emiffect=!sinytra_neoforge, additions",
	"emi_enchanting=!sinytra_neoforge, additions",
	"extra_mod_integrations=!sinytra_neoforge, additions",
	"emi_loot=!sinytra_neoforge, additions",
	"emi_ores=!sinytra_neoforge, additions",
	"emixx=!sinytra_neoforge, additions",
	"emiprofessions=!sinytra_neoforge, additions",
	"irisblockcompat=!sinytra_neoforge, additions",
	"additional_rpg_jewelry=!sinytra_neoforge, additions",
	"lne_archers=!sinytra_neoforge, additions",
	"lne_paladins=!sinytra_neoforge, additions",
	"lne_rogues=!sinytra_fabric, additions",
	"lne_wizards=!sinytra_neoforge, additions",
	"more_relics=!sinytra_neoforge, additions",
	"mrpgc_skill_tree=!sinytra_neoforge, additions",
	"sodium_extra=!sinytra_neoforge, additions",
	"reeses_sodium_options=!sinytra_neoforge, additions",
	"sspb=!sinytra_neoforge, additions",
	"more_sounds=!sinytra_neoforge, additions",
	"mr_terralith_biomesaplings=!sinytra_neoforge, additions",
	"mr_remove_terralithintromessage=!sinytra_neoforge, additions",
	"elemental_wizards_rpg=!sinytra_neoforge, additions",
	"connector=!sinytra_neoforge, !library, core",
	"fabric_api=!sinytra_neoforge, !library, core",
	"trinkets=sinytra_fabric, library",
	"accessories=library",
	"architectury=library",
	"azurelibarmor=library",
	"balm=library",
	"bookshelf=library",
	"cloth_config=library",
	"collective=library",
	"configurable=library",
	"creativecore=library",
	"curios=library",
	"fzzy_config=library",
	"gml=library",
	"konkrete=library",
	"kotlinforforge=library",
	"melody=library",
	"midnightlib=library",
	"mru=library",
	"octolib=library",
	"owo=library",
	"playeranimator=library",
	"prickle=library",
	"puzzleslib=library",
	"resourcefullib=library",
	"yet_another_config_lib_v3=library",
	"continuity=!sinytra_fabric, sinytra_neoforge",
	"bundleapi=!sinytra_neoforge, rpg_series, library",
	"more_rpg_classes=!sinytra_neoforge, rpg_series, library",
	"ranged_weapon_api=!sinytra_neoforge, rpg_series, library",
	"shield_api=!sinytra_neoforge, rpg_series, library",
	"spell_engine=!sinytra_neoforge, rpg_series, library",
	"spell_power=!sinytra_neoforge, rpg_series, library",
	"structure_pool_api=!sinytra_neoforge, rpg_series, library",
	"archers=!sinytra_neoforge, rpg_series",
	"armory_rpgs=!sinytra_neoforge, rpg_series",
	"arsenal=!sinytra_neoforge, rpg_series",
	"berserker_rpg=!sinytra_neoforge, rpg_series",
	"bettercombat=!sinytra_neoforge, rpg_series",
	"combat_roll=!sinytra_neoforge, rpg_series",
	"critical_strike=!sinytra_neoforge, rpg_series",
	"dungeon_difficulty=!sinytra_neoforge, rpg_series",
	"forcemaster_rpg=!sinytra_neoforge, rpg_series",
	"gazebo=!sinytra_neoforge, rpg_series",
	"jewelry=!sinytra_neoforge, rpg_series",
	"loot_n_explore=!sinytra_fabric, rpg_series",
	"paladins=!sinytra_neoforge, rpg_series",
	"relics_rpgs=!sinytra_neoforge, rpg_series",
	"rogues=!sinytra_neoforge, rpg_series",
	"runes=!sinytra_neoforge, rpg_series",
	"skill_tree_rpgs=!sinytra_neoforge, rpg_series",
	"village_taverns=!sinytra_neoforge, rpg_series",
	"witcher_rpg=!sinytra_neoforge, rpg_series",
	"wizards=!sinytra_neoforge, rpg_series",
	"libraryferret=!sinytra_neoforge, worldgen, library",
	"lithostitched=!sinytra_neoforge, worldgen, library",
	"terrablender=!sinytra_neoforge, worldgen, library",
	"yungsapi=!sinytra_neoforge, worldgen, library",
	"amplified_nether=!sinytra_neoforge, worldgen",
	"awesomedungeon=!sinytra_neoforge, worldgen",
	"bettervillage=!sinytra_neoforge, worldgen",
	"chunky=!sinytra_neoforge, worldgen",
	"improved_village_placement=!sinytra_neoforge, worldgen",
	"nullscape=!sinytra_neoforge, worldgen",
	"puffish_biome_dither=!sinytra_neoforge, worldgen",
	"terralith=!sinytra_neoforge, worldgen"
]

mod_parents = [
	"citresewn=citresewn_neopatcher",
	"accessories=accessories_compat_layer, bl_accessories_layer",
	"emi=emiffect, emi_enchanting, extra_mod_integrations, emi_loot, emi_ores, emixx, emiprofessions",
	"iris=irisblockcompat",
	"sodium=sodium_extra, reeses_sodium_options, sspb",
	"sounds=more_sounds",
	"archers=archers_expansion",
	"bettercombat=bettercombatextension, malfu_mods",
	"jewelry=additional_rpg_jewelry",
	"loot_n_explore=lne_archers, lne_paladins, lne_rogues, lne_wizards",
	"relics_rpgs=more_relics",
	"skill_tree_rpgs=mrpgc_skill_tree",
	"wizards=elemental_wizards_rpg",
	"chunky=chunkyborder",
	"terralith=mr_terralith_biomesaplings, mr_remove_terralithintromessage"
]

[main]
	compact_list = true
	mods_button_style = "REPLACE_REALMS"
	mod_count_location = "NONE"
	easter_eggs = false

[hide]
	show_libraries = true
	hide_badge = ["client"]
	hidden_mods = [
		"c2me_base",
		"c2me_client_uncapvd",
		"c2me_fixes_chunkio_threading_issues",
		"c2me_fixes_general_threading_issues",
		"c2me_fixes_worldgen_threading_issues",
		"c2me_fixes_worldgen_vanilla_bugs",
		"c2me_notickvd",
		"c2me_opts_allocs",
		"c2me_opts_chunkio",
		"c2me_opts_dfc",
		"c2me_opts_math",
		"c2me_opts_natives_math",
		"c2me_opts_scheduling",
		"c2me_opts_worldgen_general",
		"c2me_opts_worldgen_vanilla",
		"c2me_rewrites_chunk_serializer",
		"c2me_rewrites_chunk_system",
		"c2me_rewrites_chunkio",
		"c2me_server_utils",
		"c2me_threading_lighting",
		"cardinal_components",
		"cclayer",
		"citresewn_defaults",
		"commongroovylibrary",
		"com_github_llamalad7_mixinextras",
		"conditional_mixin",
		"connectorextras_emi_bridge",
		"connectorextras_energy_bridge",
		"connectorextras_jei_bridge",
		"connectorextras_kubejs_bridge",
		"connectorextras_modmenu_bridge",
		"connectorextras_pehkui_bridge",
		"connectorextras_rei_bridge",
		"connectorextras_terrablender_bridge",
        "extra_mod_integrations_actually_additions",
        "extra_mod_integrations_chipped",
        "extra_mod_integrations_core",
        "extra_mod_integrations_farmers_delight",
        "extra_mod_integrations_irons_spellbooks",
        "extra_mod_integrations_pneumaticcraft",
        "extra_mod_integrations_rechiseled",
        "extra_mod_integrations_reliquary",
		"fabric-api",
		"forgified_fabric_api",
		"java",
        "jei",
		"kirin",
		"kuma_api",
		"lambdynlights_api",
		"lambdynlights_runtime",
		"minecraft",
		"mixinsquared",
		"modmenu",
		"neoforge",
		"placeholder_api",
		"pride",
		"spruceui",
		"tclayer",
		"tiny_config",
		"transition",
		"trender",
		"yumi_mc_core",
		"yumi_mc_libraries"
	]
	hide_mod_links = true
	hide_mod_license = true
	hide_mod_credits = true