[camera]

	[camera.offset]
		offset_x = -0.5
		offset_y = 0.25
		offset_z = 4.0

[perspective]
	replace_default_perspective = true
	third_person_front_enabled = false

[player]
	adjust_player_transparency = false
	player_y_rot_follows_camera = true
	player_y_rot_follow_angle_limit = 15.0

	[player.turning]
		when_using_item = "NEVER"
		when_attacking = "NEVER"
		when_interacting = "NEVER"
		when_picking = "NEVER"
		turning_lock_time = 10

[crosshair]
	crosshair_type = "DYNAMIC"

	[crosshair.visibility]
		first_person = "WHEN_AIMING_OR_IN_RANGE"
		shoulder_surfing = "WHEN_AIMING"

[object_picker]

	[object_picker.pick_vector]
		pick_vector = "PLAYER"